# Autogenerated by nbdev

d = { 'settings': { 'branch': 'main',
                'doc_baseurl': '/nbdev_again',
                'doc_host': 'https://aloiswirth.github.io',
                'git_url': 'https://github.com/aloiswirth/nbdev_again',
                'lib_path': 'nbdev_again'},
  'syms': {'nbdev_again.core': {'nbdev_again.core.foo': ('core.html#foo', 'nbdev_again/core.py')}}}
