name: CI
on:  [workflow_dispatch, pull_request, push]

jobs:
  test:
    runs-on: ubuntu-latest
#    steps: [uses: fastai/workflows/nbdev-ci@master]
    steps: 
    - name: Use Node.js 20
      uses: actions/setup-node@v4
      with:
        node-version: 20
    - uses: fastai/workflows/nbdev-ci@master